import { makeStyles } from '@material-ui/core/styles'

export default makeStyles((theme) => ({
    mainCard: {
        marginTop: '50px',
        width: 450,
        bgcolor: 'background.paper',
        boxShadow: '0 0 10px',
        padding: theme.spacing(5),
        borderRadius: 20,
    },
    labelText: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontWight: 400,
        fontSize: '16px',
        lineHeight: '24px',
        color: '#000000',
    },
    textField: {
        display: 'flex',
        flexDirection: 'column',
        fontFamily: 'Poppins',
        marginTop: 13,
        background: '#FFFFFF',
        border: '1px solid #ADADAD',
        boxSizing: 'border-box',
        borderRadius: '9px',
    },
    button: {
        fontFamily: 'Poppins',
        backgroundColor: '#3f50b5',
        marginTop: 20,
        border: '1px solid #3f50b5',
        boxSizing: 'border-box',
        borderRadius: '9px',
        height: 50,
        fontSize: '16px',
        lineHeight: '24px',
        color: '#FFFFFF',
        fontWight: 500,
    },
    textFieldContainer: {
        textAlign: 'left',
        marginTop: 20,
    },
    welcomeText: {
        fontFamily: 'Poppins',
        fontStyle: 'normal',
        fontHeight: 400,
        fontSize: '21px',
        lineHeight: '32px',
    },
    welcomeClientText: {
        fontFamily: 'Poppins',
        fontWeight: 'bold',
        fontHeight: 400,
        fontSize: '21px',
        lineHeight: '32px',
        color: '#3f50b5',
    },
    donotHaveAccountText: {
        fontFamily: 'Poppins',
        fontSize: '13px',
        color: '#8D8D8D',
    },
    donotHaveAccountButton: {
        fontFamily: 'Poppins',
        fontWeight: 'bold',
        fontSize: '13px',
        color: '#3f50b5',
        cursor: 'pointer',
    },
    signinText: {
        fontFamily: 'Poppins',
        fontWeight: 500,
        fontSize: '55px',
        color: '#000000',
    },
}))
